inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

Metrics/ModuleLength:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Layout/ExtraSpacing:
  Exclude:
    - 'db/migrate/*.rb'
    - 'spec/factories/*.rb'

Lint/ScriptPermission:
  Exclude:
    - 'Rakefile'

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'config/routes.rb'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'spec/**/*'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.xls.builder'

Security/YAMLLoad:
  Exclude:
    - 'app/models/setting.rb'
    - 'db/migrate/*.rb'
    - 'lib/tasks/ffcrm/config.rake'

Style/StringLiterals:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 15
  Exclude:
    - 'db/schema.rb'

Style/WordArray:
  Exclude:
    - 'db/schema.rb'

Style/SymbolArray:
  EnforcedStyle: percent

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*_spec.rb'
    - 'spec/lib/errors_spec.rb'

# Arguably these should be fixed at a later point, but would require depreciation, aliases, etc.
Naming/PredicatePrefix:
  Exclude:
    - 'spec/support/assert_select.rb'
    - 'app/inputs/date_time_input.rb'
    - 'app/models/users/user.rb'
    - 'lib/fat_free_crm/fields.rb'
    - 'lib/fat_free_crm/mail_processor/base.rb'

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/routing/**/*.rb'
    - 'spec/lib/**/*.rb'

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20100928030600_create_openid_tables.rb'
    - 'db/migrate/20100928030617_drop_openid_tables.rb'
    - 'db/migrate/20230526211831_create_active_storage_tables.active_storage.rb'
    - 'db/migrate/20100928030627_acts_as_taggable_on_migration.rb'