inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Layout/ExtraSpacing:
  Exclude:
    - 'db/migrate/*.rb'
    - 'spec/factories/*.rb'

Lint/ScriptPermission:
  Exclude:
    - 'Rakefile'

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'config/routes.rb'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'spec/**/*'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.xls.builder'

Security/YAMLLoad:
  Exclude:
    - 'app/models/setting.rb'
    - 'db/migrate/*.rb'
    - 'lib/tasks/ffcrm/config.rake'

StringLiterals:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 15
  Exclude:
    - 'db/schema.rb'

Style/WordArray:
  Exclude:
    - 'db/schema.rb'

Style/SymbolArray:
  EnforcedStyle: percent
