version: '3'
services:
  web:
    build: .
    links:
      - db
    ports:
      - '3000:3000'
      - '80:80'
    volumes:
      - gems:/usr/local/rvm/gems
    environment:
      RAILS_ENV: 'development'
      PASSENGER_APP_ENV: 'development'
      DB_DATABASE: 'fat_free_crm_development'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: ''
      DB_HOST: 'db'
      DB_PORT: 5432
  db:
    image: postgres:12.15-alpine
    container_name: db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fat_free_crm_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - '5432:5432'
volumes:
  pgdata: {}
  gems: {}
networks:
  default:
    name: fat_free_crm_default
