import $ from 'jquery'
import jQuery from 'jquery'
import 'jquery-migrate'
import 'webpack-jquery-ui'
import 'jquery-ujs'
import 'select2/dist/js/select2.full.min.js'
import 'application'
import 'crm.js'
import 'textarea_autocomplete'
import 'search.js'
import 'crm_classes.js'
import 'crm_loginout.js'
import 'crm_tags.js'
import 'crm_sortable.js'
import 'crm_textarea_autocomplete.js'
import 'crm_select2.js'
//= require ransack_ui_jquery
import 'lists.js'
//= require autocomplete-rails
import 'datepicker.js'
import 'jquery.disable'
import 'jquery_ui_datepicker/jquery-ui-timepicker-addon'
import 'admin/fields.js'
import 'format_buttons.js'
import 'crm_comments.js'
import 'jquery_timeago'
import 'timeago.js'
import 'pagination.js'
// *****************************
import 'jquery-ui.custom'
import 'webpack-jquery-ui/css'
import 'select2/dist/css/select2.css'
import 'modalbox'
import 'rails'
import 'safari'
import 'base'
import 'header'
import 'common'
import 'fields'
import 'textarea_autocomplete'
import 'admin/fields.css'
import 'advanced_search.css'
import 'format_buttons.css'
import 'font-awesome/scss/font-awesome'
import 'lists.css'
import 'about.css'
