#!/usr/bin/env ruby

require "rubygems"
require "bundler/setup"
require "mailman"

ENV["RAILS_ENV"] ||= "test"
require File.dirname(__FILE__) + "/../config/environment"

Mailman.config.ignore_stdin = true

if Rails.env == 'test'
  Mailman.config.maildir = Rails.root.join("tmp/test_maildir")
  Mailman.config.poll_interval = 0
else
  unless Setting.mailman_pop3 && Setting.mailman_pop3[:username].present?
    puts "Please configure Mailman POP3 settings for 'Reply via email'!"
    exit 1
  end

  Mailman.config.logger = Logger.new(Rails.root.join("log/mailman_#{Rails.env}.log"))
  Mailman.config.poll_interval = Setting.mailman_poll_interval
  Mailman.config.pop3 = Setting.mailman_pop3
end

require 'fat_free_crm/mailman'
FatFreeCRM::Mailman.run
