<%
  require "ffaker"
  puts "Loading products..."

  for i in (1 .. rand(20) + 100) do
%>
product<%= i %>:
  id          : <%= i %>
  name        : <%= FFaker::Product.product_name %>
  brand       : <%= FFaker::Company.name %>
  url         : <%= %[http://example.com/] if rand(10) < 8 %>
  created_at  : <%= created_at = (rand(60) + 2).days.ago + rand(600).minutes; created_at.to_s(:db) %>
  updated_at  : <%= (created_at + rand(36_000).seconds).to_s(:db) %>
  description : <%= FFaker::Lorem.paragraph[0,255] %>
<% end %>
