#!/bin/sh

# Stash unstaged changes
git stash -q --keep-index

# Run rubocop on staged .rb files
git diff --name-only --cached --diff-filter=AM | grep '\.rb$' | xargs bundle exec rubocop
rubocop_exit_code=$?

# Run erblint on staged .js files
git diff --name-only --cached --diff-filter=AM | grep '\.js$' | xargs bundle exec erblint
erblint_exit_code=$?

# Unstash unstaged changes
git stash pop -q

# Exit with a non-zero exit code if either linter failed
if [ $rubocop_exit_code -ne 0 ] || [ $erblint_exit_code -ne 0 ]; then
  exit 1
fi

exit 0
