name: Rails Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5
    - name: Install Bundler
      run: |
        gem install bundler
    - name: Install PostgreSQL 11 client
      run: |
        sudo apt-get -yqq install libpq-dev
    - name: Set up Chromedriver
      uses: nanasess/setup-chromedriver@master
    - name: Cache Gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    - name: Install Gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Create And Migrate DB
      run: |
        cp -f spec/dummy/config/database.gh_actions.yml spec/dummy/config/database.yml
        psql -U postgres -h localhost -c "create database dummy_test;"
        RAILS_ENV=test bundle exec rails db:migrate
    - name: Run RSpec
      run: |
        bundle exec rspec